[package]
name = "bplt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.2.2"
crossterm = "0.26.1"
ratatui = "0.20.1"
reqwest = "0.11.16"
scraper = "0.16.0"
